1. Identify by inspection and give reasons why the following 
density matrices are pure states or not. Note: also check to make they’re physical/well formed and comment on that as well.  Then confirm mathematically using a basis-independent measure.  You may have issues with machine precision; where numbers may be irrational I’ve rounded in the 5th decimal place. 

In [95]:
import qutip
import numpy as np
rho_1 = qutip.Qobj([[1/6, np.sqrt(2)/6 * np.exp(1j*.777), np.sqrt(3)/6], [np.sqrt(2)/6 * np.exp(-1j*.777), 2/6,  1/np.sqrt(6) * np.exp(-1j*3.14)], [np.sqrt(3)/6, 1/np.sqrt(6) * np.exp(1j*3.14), 3/6]])

# check purity using trace(rho^2)
print(np.trace(rho_1*rho_1))

rho_2 = qutip.Qobj([[.273, .42*np.exp(-1j*np.pi/8)], [.42*np.exp(1j*np.pi/8), .727]])

# check purity using trace(rho^2)
print(np.trace(rho_2*rho_2))

(1+0j)
(0.9558579999999999+0j)


2. Take the density matrix for 1B and calculate its Bloch Vector coordinates. How does this representation confirm what you decided about 1b in the previous problem?

In [47]:
import numpy as np
import qutip
# define the density matrix
rho = qutip.Qobj([[.273, .42*np.exp(-1j * np.pi/8)], [.42*np.exp(1j * np.pi/8), .727]])

# get the bloch vector coordinates using tr(rho * sigma)
x = np.trace(rho * qutip.sigmax())
y = np.trace(rho * qutip.sigmay())
z = np.trace(rho * qutip.sigmaz())

print(x, y, z)

# get the length of the vector
r = np.sqrt(x**2 + y**2 + z**2)
print(r)

# magnitude of the vector is < 1 so is impure

(0.7760588073094808+0j) (0.3214540831866754+0j) (-0.45399999999999996+0j)
(0.9548382061899282+0j)


3. For each bell state, find the reduced density operator for each qubit, and comment on their purities

In [39]:
from numpy import trace
import qutip

# Define the bell states
bell_states = [qutip.bell_state('00'), qutip.bell_state('01'), qutip.bell_state('10'), qutip.bell_state('11')]

# Loop over the bell states
for bell_state in bell_states:
    # Compute the reduced density matrix for each qubit
    rho_1 = qutip.ptrace(bell_state * bell_state.dag(), [0])
    print('Reduced density operator qubit 1\n', rho_1.full())
    print('Reduced density operator qubit 2\n', rho_2.full())
    rho_2 = qutip.ptrace(bell_state * bell_state.dag(), [1])
    # Compute the purity of the reduced density matrix for each qubit using trace of rho^2
    purity_1 = trace(rho_1**2)
    purity_2 = trace(rho_2**2)
    # Print the purity of the reduced density matrix for each qubit
    print('Purity of rho_1: ', purity_1)
    print('Purity of rho_2: ', purity_2)

Reduced density operator qubit 1
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Reduced density operator qubit 2
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Purity of rho_1:  (0.4999999999999998+0j)
Purity of rho_2:  (0.4999999999999998+0j)
Reduced density operator qubit 1
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Reduced density operator qubit 2
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Purity of rho_1:  (0.4999999999999998+0j)
Purity of rho_2:  (0.4999999999999998+0j)
Reduced density operator qubit 1
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Reduced density operator qubit 2
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Purity of rho_1:  (0.4999999999999998+0j)
Purity of rho_2:  (0.4999999999999998+0j)
Reduced density operator qubit 1
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Reduced density operator qubit 2
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Purity of rho_1:  (0.4999999999999998+0j)
Purity of rho_2:  (0.4999999999999998+0j)


4. The state $$|\psi\rangle = \sqrt{\frac{1}{6}} |0_10_21_3\rangle - i \sqrt{\frac{1}{6}} |1_10_20_3\rangle - \sqrt{\frac{2}{6}}|0_11_21_3\rangle + i \sqrt{\frac{2}{6}}|1_11_20_3\rangle$$ is a partially separable state of three qubits. Use partial traces over 1 qubit at a time to identify which qubit is separable from the other two and write the state as a tensor product. Please use subscripts as above in your answer to keep clear which states are indciated by which kets constitutents . This problem really benefits from a computer aid. 

In [73]:
import numpy as np
import qutip

# first build the 3 qubit state using the vector
psi = qutip.Qobj([[0, np.sqrt(1/6), 0, -np.sqrt(2/6), +1j*np.sqrt(1/6), 0, -1j*np.sqrt(2/6), 0]], dims=[[1,1,1],[2,2,2]]).dag()

print(psi)

# now compute the reduced density matrix for the first qubit
rho_1 = qutip.ptrace(psi * psi.dag(), [0,1])
print('Reduced density operator qubit 1\n', rho_1.full())

# print the purity of the reduced density matrix for the first qubit traced out
purity_1 = np.trace(rho_1**2)
print('Purity of rho_1: ', purity_1)

# # now compute the reduced density matrix for the second qubit
rho_2 = qutip.ptrace(psi * psi.dag(), [1,2])
print('Reduced density operator qubit 2\n', rho_2.full())

# print the purity of the reduced density matrix for the second qubit traced out
purity_2 = np.trace(rho_2**2)
print('Purity of rho_2: ', purity_2)

# # now compute the reduced density matrix for the third qubit
rho_3 = qutip.ptrace(psi * psi.dag(), [0,2])
print('Reduced density operator qubit 3\n', rho_3.full())

# print the purity of the reduced density matrix for the third qubit traced out
purity_3 = np.trace(rho_3**2)
print('Purity of rho_3: ', purity_3)

# find that qubit 1 can be traced out and get a pure state
# thus the separable state is found by rho_3

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[ 0.        +0.j        ]
 [ 0.40824829+0.j        ]
 [ 0.        +0.j        ]
 [-0.57735027+0.j        ]
 [ 0.        -0.40824829j]
 [ 0.        +0.j        ]
 [ 0.        +0.57735027j]
 [ 0.        +0.j        ]]
Reduced density operator qubit 1
 [[ 0.16666667+0.j -0.23570226+0.j  0.        +0.j  0.        +0.j]
 [-0.23570226+0.j  0.33333333+0.j  0.        +0.j  0.        +0.j]
 [ 0.        +0.j  0.        +0.j  0.16666667+0.j -0.23570226+0.j]
 [ 0.        +0.j  0.        +0.j -0.23570226+0.j  0.33333333+0.j]]
Purity of rho_1:  (0.5+0j)
Reduced density operator qubit 2
 [[ 0.16666667+0.j  0.        +0.j -0.23570226+0.j  0.        +0.j]
 [ 0.        +0.j  0.16666667+0.j  0.        +0.j -0.23570226+0.j]
 [-0.23570226+0.j  0.        +0.j  0.33333333+0.j  0.        +0.j]
 [ 0.        +0.j -0.23570226+0.j  0.        +0.j  0.33333333+0.j]]
Purity of rho_2:  (0.5+0j)
Reduced density operator qubit 3
 [[0

5. Construct the projective measurement whose eigenstates are those of the Hadamard operator.

In [83]:
# find the eigenvectors of hadamard
eigvals, eigvecs = qutip.hadamard_transform().eigenstates()
print(eigvecs)

[Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[ 0.38268343]
  [-0.92387953]]
 Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[-0.92387953]
  [-0.38268343]]                                              ]


/tmp/ipykernel_689/915565901.py:2: DeprecationWarning: Importing functions/classes of the qip submodule directly from the namespace qutip is deprecated. Please import them from the submodule instead, e.g.
from qutip.qip.operations import cnot
from qutip.qip.circuit import QubitCircuit

  eigvals, eigvecs = qutip.hadamard_transform().eigenstates()


In [88]:
v1, v2 = eigvecs
M = v1 * v1.dag() - v2 * v2.dag()
print(M)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
